#                   _                
#   /\  /\__ _ _ __| |__   ___  _ __ 
#  / /_/ / _` | '__| '_ \ / _ \| '__|
# / __  / (_| | |  | |_) | (_) | |   
# \/ /_/ \__,_|_|  |_.__/ \___/|_|   
#                                                       
# An open-source project by TechToolbox
# https://techtoolbox.tk/
#
# Ahoy, matey! You've arrived at the configuration file, where things get scary. 
# Every single thing within this plugin is customizable (at least I tried to make it that way),
# so every message and plugin module can be modified here. If you would like to report a bug
# or suggest a feature, make sure to add an issue on the GitHub page for this plugin!
# GitHub URL: https://github.com/nkomarn/Harbor/issues

values:
  # How often (in seconds) to check if a player is in a bed (increase for slower servers)
  check: 1
  # Percent of players that need to sleep to skip night (must be 0.0 to 1.0)
  percent: 0.5

features: 
  # Toggle night skipping feature. Configure amount of players needed to skip above (percent)
  skipNight: true
  # Clear weather when skipping night
  clearWeather: true
  # Display debug information in console
  debug: false

messages:
  chat:
    # Toggle chat messages
    chat: true
    # "Night skipped" chat message
    skipped: "&eThe night has been skipped."
    # Display which player went to bed in chat
    sleeping: "&e[player] is now sleeping ([sleeping]/[online]. [needed] more needed to skip)."
    # Sent to player when they sleep with "harbor.bypass" permission
    bypass: "&eYou've been excluded from the sleep count."
  actionbar:
    # Enable/Disable actionbar message
    actionbar: true
    # Shown when some players are in bed
    sleeping: "&e[sleeping] out of [online] players are sleeping ([needed] more needed to skip)."
    # Shown when all players are in bed
    everyone: "&eEveryone is sleeping. Sweet dreams!"
  miscellaneous:
    # Prefix for Harbor command messages
    prefix: "&8&l(&6&lHarbor&8&l) "
    # Display server version in console
    running: "&7Running on version [version]."
    # Sent in console when the plugin isn't compatible with the server
    incompatible: "&7Spigot version [version] isn't compatible with Harbor."
    # Harbor reload message
    reloaded: "&7Reloaded Harbor"
    reloadError: "&7Error reloading Harbor."
    # Sent when player doesn't have permissions to run command
    permission: "&7Insufficient permissions."

# Version identifier (do not change)
version: 1.4
